### ISSUE TITLE
Style differences in .md files

### ISSUE THREAD

**Issue by pauljohn32** [adamzap/landslide#178]
I can compile your example presentaiton, but...

I can't compile the other markdown presentations I have written. Now I notice style differences among presentation based formats all called "markdown".

Mine start from R markdown in the style popularized by RStudio, which so far as I can tell is consistent with standards for markdown language on http://johnmacfarlane.net/pandoc/demo/example9/producing-slide-shows-with-pandoc.html.   I've got a slide separator \#\# and no --- betwen slides. (you can see what I mean here: http://pj.freefaculty.org/R/rmdonrmd).  

I'm new at this.  There is no accepted standard on how slide  ".md" files ought to be written?   Every program that generates slides can re-define .md?

**Comment by adamzap** [comment]
Every markdown-based slideshow generator has to make decisions on how to interpret the markup to output a slideshow instead of plain HTML.

I hope the design decisions I've made for Landslide make sense. For instance, Landslide interprets the markup that generates an `<hr>` as a slide separator.

I've always gone back to [John Gruber's Markdown Syntax Guide](http://daringfireball.net/projects/markdown/syntax) as the authority on what markdown is. On top of that, I just pass text into python's markdown module.

I understand your frustration. Markdown-based slideshow generation is a crowded space these days.

**Comment by adamzap** [comment]
Reopen this ticket if you're still having problems
